In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('sales_data.csv')

In [3]:
df

   order_id  order_date    city     product     category  quantity  price
0      1001  2025-01-10    Pune      Laptop  Electronics         2  50000
1      1002  2025-01-11  Mumbai      Mobile  Electronics         3  20000
2      1005  2025-01-13  Mumbai      Laptop  Electronics         1  50000
3      1003  2025-01-11    Pune  Headphones  Accessories         5   2000
4      1004  2025-01-12  Nagpur    Keyboard  Accessories         4   1500

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    5 non-null      int64
 1   order_date  5 non-null      object
 2   city        5 non-null      object
 3   product     5 non-null      object
 4   category    5 non-null      object
 5   quantity    5 non-null      int64
 6   price       5 non-null      int64
dtypes: int64(3), object(4)
memory usage: 412.0+ bytes

In [5]:
df.describe()

          order_id  quantity        price
count     5.000000  5.000000      5.00000
mean   1003.000000  3.000000  24700.00000
std       1.581139  1.581139  24268.29207
min    1001.000000  1.000000   1500.00000
25%    1002.000000  2.000000   2000.00000
50%    1003.000000  3.000000  20000.00000
75%    1004.000000  4.000000  50000.00000
max    1005.000000  5.000000  50000.00000

In [6]:
df['total_sales'] = df['quantity'] *df['price']

In [7]:
df

,order_id,order_date,city,product,category,quantity,price,total_sales
0,1001,2025-01-10,Pune,Laptop,Electronics,2,50000,100000
1,1002,2025-01-11,Mumbai,Mobile,Electronics,3,20000,60000
2,1005,2025-01-13,Mumbai,Laptop,Electronics,1,50000,50000
3,1003,2025-01-11,Pune,Headphones,Accessories,5,2000,10000
4,1004,2025-01-12,Nagpur,Keyboard,Accessories,4,1500,6000

In [8]:
total_revenue = sum(df['total_sales'])

In [9]:
total_revenue

226000

In [10]:
most_sold = df.groupby('product')['quantity'].sum().sort_values(ascending=False)
print(most_sold)

product
Headphones    5
Keyboard      4
Laptop        3
Mobile        3
Name: quantity, dtype: int64

In [11]:
print(most_sold.idxmax())

Headphones

In [12]:
city_sales = df.groupby('city')['total_sales'].sum()
print(city_sales)

city
Mumbai    110000
Nagpur      6000
Pune      110000
Name: total_sales, dtype: int64

In [13]:
summary = df.describe()
print(summary)

          order_id  quantity        price    total_sales
count     5.000000  5.000000      5.00000       5.000000
mean   1003.000000  3.000000  24700.00000   45200.000000
std       1.581139  1.581139  24268.29207   38796.907093
min    1001.000000  1.000000   1500.00000    6000.000000
25%    1002.000000  2.000000   2000.00000   10000.000000
50%    1003.000000  3.000000  20000.00000   50000.000000
75%    1004.000000  4.000000  50000.00000   60000.000000
max    1005.000000  5.000000  50000.00000  100000.000000